//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSILearningManagementSystem.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICourseService")]
    public interface ICourseService {
        
        // CODEGEN: Parameter 'GetCoursesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetCourses", ReplyAction="http://tempuri.org/ICourseService/GetCoursesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.GetCoursesResponse GetCourses(NSILearningManagementSystem.ServiceReference1.GetCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetCourses", ReplyAction="http://tempuri.org/ICourseService/GetCoursesResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetCoursesResponse> GetCoursesAsync(NSILearningManagementSystem.ServiceReference1.GetCoursesRequest request);
        
        // CODEGEN: Parameter 'GetInstructorCoursesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetInstructorCourses", ReplyAction="http://tempuri.org/ICourseService/GetInstructorCoursesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesResponse GetInstructorCourses(NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetInstructorCourses", ReplyAction="http://tempuri.org/ICourseService/GetInstructorCoursesResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesResponse> GetInstructorCoursesAsync(NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesRequest request);
        
        // CODEGEN: Parameter 'GetInstructorCourseModuleDetailsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetInstructorCourseModuleDetails", ReplyAction="http://tempuri.org/ICourseService/GetInstructorCourseModuleDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsResponse GetInstructorCourseModuleDetails(NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetInstructorCourseModuleDetails", ReplyAction="http://tempuri.org/ICourseService/GetInstructorCourseModuleDetailsResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsResponse> GetInstructorCourseModuleDetailsAsync(NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsRequest request);
        
        // CODEGEN: Parameter 'SelectCourseTraineeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectCourseTrainee", ReplyAction="http://tempuri.org/ICourseService/SelectCourseTraineeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeResponse SelectCourseTrainee(NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectCourseTrainee", ReplyAction="http://tempuri.org/ICourseService/SelectCourseTraineeResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeResponse> SelectCourseTraineeAsync(NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeRequest request);
        
        // CODEGEN: Parameter 'SelectModuleTraineeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectModuleTrainee", ReplyAction="http://tempuri.org/ICourseService/SelectModuleTraineeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeResponse SelectModuleTrainee(NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectModuleTrainee", ReplyAction="http://tempuri.org/ICourseService/SelectModuleTraineeResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeResponse> SelectModuleTraineeAsync(NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeRequest request);
        
        // CODEGEN: Parameter 'SelectTraineeDashboardDetailsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectTraineeDashboardDetails", ReplyAction="http://tempuri.org/ICourseService/SelectTraineeDashboardDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsResponse SelectTraineeDashboardDetails(NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectTraineeDashboardDetails", ReplyAction="http://tempuri.org/ICourseService/SelectTraineeDashboardDetailsResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsResponse> SelectTraineeDashboardDetailsAsync(NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsRequest request);
        
        // CODEGEN: Parameter 'InsertAssignmentResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/InsertAssignment", ReplyAction="http://tempuri.org/ICourseService/InsertAssignmentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.InsertAssignmentResponse InsertAssignment(NSILearningManagementSystem.ServiceReference1.InsertAssignmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/InsertAssignment", ReplyAction="http://tempuri.org/ICourseService/InsertAssignmentResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.InsertAssignmentResponse> InsertAssignmentAsync(NSILearningManagementSystem.ServiceReference1.InsertAssignmentRequest request);
        
        // CODEGEN: Parameter 'SelectAssignmentResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectAssignment", ReplyAction="http://tempuri.org/ICourseService/SelectAssignmentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.SelectAssignmentResponse SelectAssignment(NSILearningManagementSystem.ServiceReference1.SelectAssignmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectAssignment", ReplyAction="http://tempuri.org/ICourseService/SelectAssignmentResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectAssignmentResponse> SelectAssignmentAsync(NSILearningManagementSystem.ServiceReference1.SelectAssignmentRequest request);
        
        // CODEGEN: Parameter 'SelectTraineeCourseLinkResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectTraineeCourseLink", ReplyAction="http://tempuri.org/ICourseService/SelectTraineeCourseLinkResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkResponse SelectTraineeCourseLink(NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectTraineeCourseLink", ReplyAction="http://tempuri.org/ICourseService/SelectTraineeCourseLinkResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkResponse> SelectTraineeCourseLinkAsync(NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkRequest request);
        
        // CODEGEN: Parameter 'SelectSurveyQuestionsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectSurveyQuestions", ReplyAction="http://tempuri.org/ICourseService/SelectSurveyQuestionsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsResponse SelectSurveyQuestions(NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SelectSurveyQuestions", ReplyAction="http://tempuri.org/ICourseService/SelectSurveyQuestionsResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsResponse> SelectSurveyQuestionsAsync(NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsRequest request);
        
        // CODEGEN: Parameter 'file' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Download", ReplyAction="http://tempuri.org/ICourseService/DownloadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.DownloadResponse Download(NSILearningManagementSystem.ServiceReference1.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Download", ReplyAction="http://tempuri.org/ICourseService/DownloadResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.DownloadResponse> DownloadAsync(NSILearningManagementSystem.ServiceReference1.DownloadRequest request);
        
        // CODEGEN: Parameter 'UploadResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Upload", ReplyAction="http://tempuri.org/ICourseService/UploadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.UploadResponse Upload(NSILearningManagementSystem.ServiceReference1.UploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Upload", ReplyAction="http://tempuri.org/ICourseService/UploadResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.UploadResponse> UploadAsync(NSILearningManagementSystem.ServiceReference1.UploadRequest request);
        
        // CODEGEN: Parameter 'GetValueResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetValue", ReplyAction="http://tempuri.org/ICourseService/GetValueResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NSILearningManagementSystem.ServiceReference1.GetValueResponse GetValue(NSILearningManagementSystem.ServiceReference1.GetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetValue", ReplyAction="http://tempuri.org/ICourseService/GetValueResponse")]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetValueResponse> GetValueAsync(NSILearningManagementSystem.ServiceReference1.GetValueRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFLearningManagementSystem")]
    public partial class Crse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string courseCodeField;
        
        private decimal courseCostField;
        
        private bool courseCostFieldSpecified;
        
        private string courseNameField;
        
        private System.Data.DataTable crseTableField;
        
        private string descriptionField;
        
        private string instructorField;
        
        private int moduleCountField;
        
        private bool moduleCountFieldSpecified;
        
        private string moduleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CourseCode {
            get {
                return this.courseCodeField;
            }
            set {
                this.courseCodeField = value;
                this.RaisePropertyChanged("CourseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal CourseCost {
            get {
                return this.courseCostField;
            }
            set {
                this.courseCostField = value;
                this.RaisePropertyChanged("CourseCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CourseCostSpecified {
            get {
                return this.courseCostFieldSpecified;
            }
            set {
                this.courseCostFieldSpecified = value;
                this.RaisePropertyChanged("CourseCostSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CourseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
                this.RaisePropertyChanged("CourseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Data.DataTable CrseTable {
            get {
                return this.crseTableField;
            }
            set {
                this.crseTableField = value;
                this.RaisePropertyChanged("CrseTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Instructor {
            get {
                return this.instructorField;
            }
            set {
                this.instructorField = value;
                this.RaisePropertyChanged("Instructor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ModuleCount {
            get {
                return this.moduleCountField;
            }
            set {
                this.moduleCountField = value;
                this.RaisePropertyChanged("ModuleCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModuleCountSpecified {
            get {
                return this.moduleCountFieldSpecified;
            }
            set {
                this.moduleCountFieldSpecified = value;
                this.RaisePropertyChanged("ModuleCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string ModuleName {
            get {
                return this.moduleNameField;
            }
            set {
                this.moduleNameField = value;
                this.RaisePropertyChanged("ModuleName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFLearningManagementSystem")]
    public partial class TraineeSurveyLink : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable traineeSurveyLinkTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataTable TraineeSurveyLinkTable {
            get {
                return this.traineeSurveyLinkTableField;
            }
            set {
                this.traineeSurveyLinkTableField = value;
                this.RaisePropertyChanged("TraineeSurveyLinkTable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFLearningManagementSystem")]
    public partial class TraineeCrseLink : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable traineeCrseLinkTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataTable TraineeCrseLinkTable {
            get {
                return this.traineeCrseLinkTableField;
            }
            set {
                this.traineeCrseLinkTableField = value;
                this.RaisePropertyChanged("TraineeCrseLinkTable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFLearningManagementSystem")]
    public partial class Assignment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string assignDateField;
        
        private string assignmentIDField;
        
        private string assignmentNameField;
        
        private System.Data.DataTable assignmentTableField;
        
        private string courseIDField;
        
        private string dueDateField;
        
        private string fileNameField;
        
        private string instrattField;
        
        private string instructorIDField;
        
        private string moduleIDField;
        
        private short statusField;
        
        private bool statusFieldSpecified;
        
        private string traineeInstrField;
        
        private string userIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AssignDate {
            get {
                return this.assignDateField;
            }
            set {
                this.assignDateField = value;
                this.RaisePropertyChanged("AssignDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AssignmentID {
            get {
                return this.assignmentIDField;
            }
            set {
                this.assignmentIDField = value;
                this.RaisePropertyChanged("AssignmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string AssignmentName {
            get {
                return this.assignmentNameField;
            }
            set {
                this.assignmentNameField = value;
                this.RaisePropertyChanged("AssignmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Data.DataTable AssignmentTable {
            get {
                return this.assignmentTableField;
            }
            set {
                this.assignmentTableField = value;
                this.RaisePropertyChanged("AssignmentTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CourseID {
            get {
                return this.courseIDField;
            }
            set {
                this.courseIDField = value;
                this.RaisePropertyChanged("CourseID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
                this.RaisePropertyChanged("DueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Instratt {
            get {
                return this.instrattField;
            }
            set {
                this.instrattField = value;
                this.RaisePropertyChanged("Instratt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string InstructorID {
            get {
                return this.instructorIDField;
            }
            set {
                this.instructorIDField = value;
                this.RaisePropertyChanged("InstructorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string ModuleID {
            get {
                return this.moduleIDField;
            }
            set {
                this.moduleIDField = value;
                this.RaisePropertyChanged("ModuleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public short Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string TraineeInstr {
            get {
                return this.traineeInstrField;
            }
            set {
                this.traineeInstrField = value;
                this.RaisePropertyChanged("TraineeInstr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFLearningManagementSystem")]
    public partial class TraineeCrseStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable traineeCrseStatusTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataTable TraineeCrseStatusTable {
            get {
                return this.traineeCrseStatusTableField;
            }
            set {
                this.traineeCrseStatusTableField = value;
                this.RaisePropertyChanged("TraineeCrseStatusTable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFLearningManagementSystem")]
    public partial class TraineeMdl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable traineeMdlTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataTable TraineeMdlTable {
            get {
                return this.traineeMdlTableField;
            }
            set {
                this.traineeMdlTableField = value;
                this.RaisePropertyChanged("TraineeMdlTable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFLearningManagementSystem")]
    public partial class TraineeCrse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable traineeCrseTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataTable TraineeCrseTable {
            get {
                return this.traineeCrseTableField;
            }
            set {
                this.traineeCrseTableField = value;
                this.RaisePropertyChanged("TraineeCrseTable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFLearningManagementSystem")]
    public partial class InstrCrseMdle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable instrCrseMdleTableField;
        
        private System.Data.DataTable instrCrseTeamsLinkTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataTable InstrCrseMdleTable {
            get {
                return this.instrCrseMdleTableField;
            }
            set {
                this.instrCrseMdleTableField = value;
                this.RaisePropertyChanged("InstrCrseMdleTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Data.DataTable InstrCrseTeamsLinkTable {
            get {
                return this.instrCrseTeamsLinkTableField;
            }
            set {
                this.instrCrseTeamsLinkTableField = value;
                this.RaisePropertyChanged("InstrCrseTeamsLinkTable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFLearningManagementSystem")]
    public partial class InstrCrse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable instrCrseTableField;
        
        private System.Data.DataTable studCrseTableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Data.DataTable InstrCrseTable {
            get {
                return this.instrCrseTableField;
            }
            set {
                this.instrCrseTableField = value;
                this.RaisePropertyChanged("InstrCrseTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Data.DataTable StudCrseTable {
            get {
                return this.studCrseTableField;
            }
            set {
                this.studCrseTableField = value;
                this.RaisePropertyChanged("StudCrseTable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourses", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CourseID;
        
        public GetCoursesRequest() {
        }
        
        public GetCoursesRequest(int CourseID) {
            this.CourseID = CourseID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCoursesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.Crse GetCoursesResult;
        
        public GetCoursesResponse() {
        }
        
        public GetCoursesResponse(NSILearningManagementSystem.ServiceReference1.Crse GetCoursesResult) {
            this.GetCoursesResult = GetCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInstructorCourses", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInstructorCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int flag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CourseID;
        
        public GetInstructorCoursesRequest() {
        }
        
        public GetInstructorCoursesRequest(int flag, int CourseID) {
            this.flag = flag;
            this.CourseID = CourseID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInstructorCoursesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInstructorCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.InstrCrse GetInstructorCoursesResult;
        
        public GetInstructorCoursesResponse() {
        }
        
        public GetInstructorCoursesResponse(NSILearningManagementSystem.ServiceReference1.InstrCrse GetInstructorCoursesResult) {
            this.GetInstructorCoursesResult = GetInstructorCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInstructorCourseModuleDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInstructorCourseModuleDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int flag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int InstructorID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int CourseID;
        
        public GetInstructorCourseModuleDetailsRequest() {
        }
        
        public GetInstructorCourseModuleDetailsRequest(int flag, int InstructorID, int CourseID) {
            this.flag = flag;
            this.InstructorID = InstructorID;
            this.CourseID = CourseID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInstructorCourseModuleDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInstructorCourseModuleDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.InstrCrseMdle GetInstructorCourseModuleDetailsResult;
        
        public GetInstructorCourseModuleDetailsResponse() {
        }
        
        public GetInstructorCourseModuleDetailsResponse(NSILearningManagementSystem.ServiceReference1.InstrCrseMdle GetInstructorCourseModuleDetailsResult) {
            this.GetInstructorCourseModuleDetailsResult = GetInstructorCourseModuleDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectCourseTrainee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectCourseTraineeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long TraineeID;
        
        public SelectCourseTraineeRequest() {
        }
        
        public SelectCourseTraineeRequest(long TraineeID) {
            this.TraineeID = TraineeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectCourseTraineeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectCourseTraineeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.TraineeCrse SelectCourseTraineeResult;
        
        public SelectCourseTraineeResponse() {
        }
        
        public SelectCourseTraineeResponse(NSILearningManagementSystem.ServiceReference1.TraineeCrse SelectCourseTraineeResult) {
            this.SelectCourseTraineeResult = SelectCourseTraineeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectModuleTrainee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectModuleTraineeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CourseID;
        
        public SelectModuleTraineeRequest() {
        }
        
        public SelectModuleTraineeRequest(int CourseID) {
            this.CourseID = CourseID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectModuleTraineeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectModuleTraineeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.TraineeMdl SelectModuleTraineeResult;
        
        public SelectModuleTraineeResponse() {
        }
        
        public SelectModuleTraineeResponse(NSILearningManagementSystem.ServiceReference1.TraineeMdl SelectModuleTraineeResult) {
            this.SelectModuleTraineeResult = SelectModuleTraineeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectTraineeDashboardDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectTraineeDashboardDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long TraineeID;
        
        public SelectTraineeDashboardDetailsRequest() {
        }
        
        public SelectTraineeDashboardDetailsRequest(long TraineeID) {
            this.TraineeID = TraineeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectTraineeDashboardDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectTraineeDashboardDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.TraineeCrseStatus SelectTraineeDashboardDetailsResult;
        
        public SelectTraineeDashboardDetailsResponse() {
        }
        
        public SelectTraineeDashboardDetailsResponse(NSILearningManagementSystem.ServiceReference1.TraineeCrseStatus SelectTraineeDashboardDetailsResult) {
            this.SelectTraineeDashboardDetailsResult = SelectTraineeDashboardDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertAssignment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertAssignmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.Assignment _Asgmt;
        
        public InsertAssignmentRequest() {
        }
        
        public InsertAssignmentRequest(NSILearningManagementSystem.ServiceReference1.Assignment _Asgmt) {
            this._Asgmt = _Asgmt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertAssignmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertAssignmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InsertAssignmentResult;
        
        public InsertAssignmentResponse() {
        }
        
        public InsertAssignmentResponse(string InsertAssignmentResult) {
            this.InsertAssignmentResult = InsertAssignmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectAssignment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectAssignmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int flag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int AssignmentID;
        
        public SelectAssignmentRequest() {
        }
        
        public SelectAssignmentRequest(int flag, int AssignmentID) {
            this.flag = flag;
            this.AssignmentID = AssignmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectAssignmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectAssignmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.Assignment SelectAssignmentResult;
        
        public SelectAssignmentResponse() {
        }
        
        public SelectAssignmentResponse(NSILearningManagementSystem.ServiceReference1.Assignment SelectAssignmentResult) {
            this.SelectAssignmentResult = SelectAssignmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectTraineeCourseLink", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectTraineeCourseLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long TraineeID;
        
        public SelectTraineeCourseLinkRequest() {
        }
        
        public SelectTraineeCourseLinkRequest(long TraineeID) {
            this.TraineeID = TraineeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectTraineeCourseLinkResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectTraineeCourseLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.TraineeCrseLink SelectTraineeCourseLinkResult;
        
        public SelectTraineeCourseLinkResponse() {
        }
        
        public SelectTraineeCourseLinkResponse(NSILearningManagementSystem.ServiceReference1.TraineeCrseLink SelectTraineeCourseLinkResult) {
            this.SelectTraineeCourseLinkResult = SelectTraineeCourseLinkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectSurveyQuestions", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectSurveyQuestionsRequest {
        
        public SelectSurveyQuestionsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectSurveyQuestionsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectSurveyQuestionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NSILearningManagementSystem.ServiceReference1.TraineeSurveyLink SelectSurveyQuestionsResult;
        
        public SelectSurveyQuestionsResponse() {
        }
        
        public SelectSurveyQuestionsResponse(NSILearningManagementSystem.ServiceReference1.TraineeSurveyLink SelectSurveyQuestionsResult) {
            this.SelectSurveyQuestionsResult = SelectSurveyQuestionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Download", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string file;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string file) {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream DownloadResult;
        
        public DownloadResponse() {
        }
        
        public DownloadResponse(System.IO.Stream DownloadResult) {
            this.DownloadResult = DownloadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream input;
        
        public UploadRequest() {
        }
        
        public UploadRequest(System.IO.Stream input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UploadResult;
        
        public UploadResponse() {
        }
        
        public UploadResponse(string UploadResult) {
            this.UploadResult = UploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string msg;
        
        public GetValueRequest() {
        }
        
        public GetValueRequest(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetValueResult;
        
        public GetValueResponse() {
        }
        
        public GetValueResponse(string GetValueResult) {
            this.GetValueResult = GetValueResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseServiceChannel : NSILearningManagementSystem.ServiceReference1.ICourseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseServiceClient : System.ServiceModel.ClientBase<NSILearningManagementSystem.ServiceReference1.ICourseService>, NSILearningManagementSystem.ServiceReference1.ICourseService {
        
        public CourseServiceClient() {
        }
        
        public CourseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.GetCoursesResponse NSILearningManagementSystem.ServiceReference1.ICourseService.GetCourses(NSILearningManagementSystem.ServiceReference1.GetCoursesRequest request) {
            return base.Channel.GetCourses(request);
        }
        
        public NSILearningManagementSystem.ServiceReference1.Crse GetCourses(int CourseID) {
            NSILearningManagementSystem.ServiceReference1.GetCoursesRequest inValue = new NSILearningManagementSystem.ServiceReference1.GetCoursesRequest();
            inValue.CourseID = CourseID;
            NSILearningManagementSystem.ServiceReference1.GetCoursesResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).GetCourses(inValue);
            return retVal.GetCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetCoursesResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.GetCoursesAsync(NSILearningManagementSystem.ServiceReference1.GetCoursesRequest request) {
            return base.Channel.GetCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetCoursesResponse> GetCoursesAsync(int CourseID) {
            NSILearningManagementSystem.ServiceReference1.GetCoursesRequest inValue = new NSILearningManagementSystem.ServiceReference1.GetCoursesRequest();
            inValue.CourseID = CourseID;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).GetCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesResponse NSILearningManagementSystem.ServiceReference1.ICourseService.GetInstructorCourses(NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesRequest request) {
            return base.Channel.GetInstructorCourses(request);
        }
        
        public NSILearningManagementSystem.ServiceReference1.InstrCrse GetInstructorCourses(int flag, int CourseID) {
            NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesRequest inValue = new NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesRequest();
            inValue.flag = flag;
            inValue.CourseID = CourseID;
            NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).GetInstructorCourses(inValue);
            return retVal.GetInstructorCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.GetInstructorCoursesAsync(NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesRequest request) {
            return base.Channel.GetInstructorCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesResponse> GetInstructorCoursesAsync(int flag, int CourseID) {
            NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesRequest inValue = new NSILearningManagementSystem.ServiceReference1.GetInstructorCoursesRequest();
            inValue.flag = flag;
            inValue.CourseID = CourseID;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).GetInstructorCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsResponse NSILearningManagementSystem.ServiceReference1.ICourseService.GetInstructorCourseModuleDetails(NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsRequest request) {
            return base.Channel.GetInstructorCourseModuleDetails(request);
        }
        
        public NSILearningManagementSystem.ServiceReference1.InstrCrseMdle GetInstructorCourseModuleDetails(int flag, int InstructorID, int CourseID) {
            NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsRequest inValue = new NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsRequest();
            inValue.flag = flag;
            inValue.InstructorID = InstructorID;
            inValue.CourseID = CourseID;
            NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).GetInstructorCourseModuleDetails(inValue);
            return retVal.GetInstructorCourseModuleDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.GetInstructorCourseModuleDetailsAsync(NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsRequest request) {
            return base.Channel.GetInstructorCourseModuleDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsResponse> GetInstructorCourseModuleDetailsAsync(int flag, int InstructorID, int CourseID) {
            NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsRequest inValue = new NSILearningManagementSystem.ServiceReference1.GetInstructorCourseModuleDetailsRequest();
            inValue.flag = flag;
            inValue.InstructorID = InstructorID;
            inValue.CourseID = CourseID;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).GetInstructorCourseModuleDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeResponse NSILearningManagementSystem.ServiceReference1.ICourseService.SelectCourseTrainee(NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeRequest request) {
            return base.Channel.SelectCourseTrainee(request);
        }
        
        public NSILearningManagementSystem.ServiceReference1.TraineeCrse SelectCourseTrainee(long TraineeID) {
            NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeRequest();
            inValue.TraineeID = TraineeID;
            NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectCourseTrainee(inValue);
            return retVal.SelectCourseTraineeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.SelectCourseTraineeAsync(NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeRequest request) {
            return base.Channel.SelectCourseTraineeAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeResponse> SelectCourseTraineeAsync(long TraineeID) {
            NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectCourseTraineeRequest();
            inValue.TraineeID = TraineeID;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectCourseTraineeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeResponse NSILearningManagementSystem.ServiceReference1.ICourseService.SelectModuleTrainee(NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeRequest request) {
            return base.Channel.SelectModuleTrainee(request);
        }
        
        public NSILearningManagementSystem.ServiceReference1.TraineeMdl SelectModuleTrainee(int CourseID) {
            NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeRequest();
            inValue.CourseID = CourseID;
            NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectModuleTrainee(inValue);
            return retVal.SelectModuleTraineeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.SelectModuleTraineeAsync(NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeRequest request) {
            return base.Channel.SelectModuleTraineeAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeResponse> SelectModuleTraineeAsync(int CourseID) {
            NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectModuleTraineeRequest();
            inValue.CourseID = CourseID;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectModuleTraineeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsResponse NSILearningManagementSystem.ServiceReference1.ICourseService.SelectTraineeDashboardDetails(NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsRequest request) {
            return base.Channel.SelectTraineeDashboardDetails(request);
        }
        
        public NSILearningManagementSystem.ServiceReference1.TraineeCrseStatus SelectTraineeDashboardDetails(long TraineeID) {
            NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsRequest();
            inValue.TraineeID = TraineeID;
            NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectTraineeDashboardDetails(inValue);
            return retVal.SelectTraineeDashboardDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.SelectTraineeDashboardDetailsAsync(NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsRequest request) {
            return base.Channel.SelectTraineeDashboardDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsResponse> SelectTraineeDashboardDetailsAsync(long TraineeID) {
            NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectTraineeDashboardDetailsRequest();
            inValue.TraineeID = TraineeID;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectTraineeDashboardDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.InsertAssignmentResponse NSILearningManagementSystem.ServiceReference1.ICourseService.InsertAssignment(NSILearningManagementSystem.ServiceReference1.InsertAssignmentRequest request) {
            return base.Channel.InsertAssignment(request);
        }
        
        public string InsertAssignment(NSILearningManagementSystem.ServiceReference1.Assignment _Asgmt) {
            NSILearningManagementSystem.ServiceReference1.InsertAssignmentRequest inValue = new NSILearningManagementSystem.ServiceReference1.InsertAssignmentRequest();
            inValue._Asgmt = _Asgmt;
            NSILearningManagementSystem.ServiceReference1.InsertAssignmentResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).InsertAssignment(inValue);
            return retVal.InsertAssignmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.InsertAssignmentResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.InsertAssignmentAsync(NSILearningManagementSystem.ServiceReference1.InsertAssignmentRequest request) {
            return base.Channel.InsertAssignmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.InsertAssignmentResponse> InsertAssignmentAsync(NSILearningManagementSystem.ServiceReference1.Assignment _Asgmt) {
            NSILearningManagementSystem.ServiceReference1.InsertAssignmentRequest inValue = new NSILearningManagementSystem.ServiceReference1.InsertAssignmentRequest();
            inValue._Asgmt = _Asgmt;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).InsertAssignmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.SelectAssignmentResponse NSILearningManagementSystem.ServiceReference1.ICourseService.SelectAssignment(NSILearningManagementSystem.ServiceReference1.SelectAssignmentRequest request) {
            return base.Channel.SelectAssignment(request);
        }
        
        public NSILearningManagementSystem.ServiceReference1.Assignment SelectAssignment(int flag, int AssignmentID) {
            NSILearningManagementSystem.ServiceReference1.SelectAssignmentRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectAssignmentRequest();
            inValue.flag = flag;
            inValue.AssignmentID = AssignmentID;
            NSILearningManagementSystem.ServiceReference1.SelectAssignmentResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectAssignment(inValue);
            return retVal.SelectAssignmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectAssignmentResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.SelectAssignmentAsync(NSILearningManagementSystem.ServiceReference1.SelectAssignmentRequest request) {
            return base.Channel.SelectAssignmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectAssignmentResponse> SelectAssignmentAsync(int flag, int AssignmentID) {
            NSILearningManagementSystem.ServiceReference1.SelectAssignmentRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectAssignmentRequest();
            inValue.flag = flag;
            inValue.AssignmentID = AssignmentID;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectAssignmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkResponse NSILearningManagementSystem.ServiceReference1.ICourseService.SelectTraineeCourseLink(NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkRequest request) {
            return base.Channel.SelectTraineeCourseLink(request);
        }
        
        public NSILearningManagementSystem.ServiceReference1.TraineeCrseLink SelectTraineeCourseLink(long TraineeID) {
            NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkRequest();
            inValue.TraineeID = TraineeID;
            NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectTraineeCourseLink(inValue);
            return retVal.SelectTraineeCourseLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.SelectTraineeCourseLinkAsync(NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkRequest request) {
            return base.Channel.SelectTraineeCourseLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkResponse> SelectTraineeCourseLinkAsync(long TraineeID) {
            NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectTraineeCourseLinkRequest();
            inValue.TraineeID = TraineeID;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectTraineeCourseLinkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsResponse NSILearningManagementSystem.ServiceReference1.ICourseService.SelectSurveyQuestions(NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsRequest request) {
            return base.Channel.SelectSurveyQuestions(request);
        }
        
        public NSILearningManagementSystem.ServiceReference1.TraineeSurveyLink SelectSurveyQuestions() {
            NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsRequest();
            NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectSurveyQuestions(inValue);
            return retVal.SelectSurveyQuestionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.SelectSurveyQuestionsAsync(NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsRequest request) {
            return base.Channel.SelectSurveyQuestionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsResponse> SelectSurveyQuestionsAsync() {
            NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsRequest inValue = new NSILearningManagementSystem.ServiceReference1.SelectSurveyQuestionsRequest();
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).SelectSurveyQuestionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.DownloadResponse NSILearningManagementSystem.ServiceReference1.ICourseService.Download(NSILearningManagementSystem.ServiceReference1.DownloadRequest request) {
            return base.Channel.Download(request);
        }
        
        public System.IO.Stream Download(string file) {
            NSILearningManagementSystem.ServiceReference1.DownloadRequest inValue = new NSILearningManagementSystem.ServiceReference1.DownloadRequest();
            inValue.file = file;
            NSILearningManagementSystem.ServiceReference1.DownloadResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).Download(inValue);
            return retVal.DownloadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.DownloadResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.DownloadAsync(NSILearningManagementSystem.ServiceReference1.DownloadRequest request) {
            return base.Channel.DownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.DownloadResponse> DownloadAsync(string file) {
            NSILearningManagementSystem.ServiceReference1.DownloadRequest inValue = new NSILearningManagementSystem.ServiceReference1.DownloadRequest();
            inValue.file = file;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).DownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.UploadResponse NSILearningManagementSystem.ServiceReference1.ICourseService.Upload(NSILearningManagementSystem.ServiceReference1.UploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public string Upload(System.IO.Stream input) {
            NSILearningManagementSystem.ServiceReference1.UploadRequest inValue = new NSILearningManagementSystem.ServiceReference1.UploadRequest();
            inValue.input = input;
            NSILearningManagementSystem.ServiceReference1.UploadResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).Upload(inValue);
            return retVal.UploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.UploadResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.UploadAsync(NSILearningManagementSystem.ServiceReference1.UploadRequest request) {
            return base.Channel.UploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.UploadResponse> UploadAsync(System.IO.Stream input) {
            NSILearningManagementSystem.ServiceReference1.UploadRequest inValue = new NSILearningManagementSystem.ServiceReference1.UploadRequest();
            inValue.input = input;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).UploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NSILearningManagementSystem.ServiceReference1.GetValueResponse NSILearningManagementSystem.ServiceReference1.ICourseService.GetValue(NSILearningManagementSystem.ServiceReference1.GetValueRequest request) {
            return base.Channel.GetValue(request);
        }
        
        public string GetValue(string msg) {
            NSILearningManagementSystem.ServiceReference1.GetValueRequest inValue = new NSILearningManagementSystem.ServiceReference1.GetValueRequest();
            inValue.msg = msg;
            NSILearningManagementSystem.ServiceReference1.GetValueResponse retVal = ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).GetValue(inValue);
            return retVal.GetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetValueResponse> NSILearningManagementSystem.ServiceReference1.ICourseService.GetValueAsync(NSILearningManagementSystem.ServiceReference1.GetValueRequest request) {
            return base.Channel.GetValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<NSILearningManagementSystem.ServiceReference1.GetValueResponse> GetValueAsync(string msg) {
            NSILearningManagementSystem.ServiceReference1.GetValueRequest inValue = new NSILearningManagementSystem.ServiceReference1.GetValueRequest();
            inValue.msg = msg;
            return ((NSILearningManagementSystem.ServiceReference1.ICourseService)(this)).GetValueAsync(inValue);
        }
    }
}
